### ISSUE TITLE
Add auto-configuration for MongoDB transactions

### ISSUE THREAD

**Issue by nkolosnjaji** [spring-projects-experimental/spring-modulith#175]
`@ApplicationModuleListener` needs transactional support.
In case of Mongo, it would be nice to autoconfigure `MongoTransactionManager` in `MongoDbEventPublicationAutoConfiguration` with `@ConditionalOnMissingBean`

I can create PR.

**Comment by odrotbohm** [comment]
While I can see your point, I wonder whether Spring Modulith is the right place for that auto-configuration. For relational databases, that support is configured in Spring Boot itself and I would like to avoid an asymmetry in that regard. I'll bring this up with the Boot team.

**Comment by odrotbohm** [comment]
This should be in place now. I've decided to keep the auto-configuration in Spring Modulith as enabling transactions requires a replica set setup for the MongoDB instance connecting to. That's why it makes more sense to keep the configuration close to the Event Publication Registry as that's the one requiring transactions for MongoDB in the first place. The auto-configuration can be disabled by setting the `spring.modulith.events.mongobd.transaction-management.enabled` to `false`.
